### ISSUE TITLE
1.20.4 - Do not load (Unsupported API version 1.21)

### ISSUE THREAD

**Issue by jan-osicka** [ergor/hsrails#12]
Hello, 

I wanted to try this plugin as it is something, which would perfectly fit my theme. However it looks like the version 1.20.4 is not supported. 
I am running 1.20.4 (latest purpur build for this version), Java 21 with Aikar's Flags. 

Is it possible to add support for this version as well? Thank you! ❤️ 

`[ModernPluginLoadingStrategy] Could not load plugin 'hsrails.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.21
	at org.bukkit.craftbukkit.v1_20_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:389) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:521) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:311) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.4.jar:git-Purpur-2176]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]`

**Comment by ergor** [comment]
Hi @jan-osicka , thank you for reporting. I will look into this as soon as possible

**Comment by ergor** [comment]
I have uploaded a hotfix to bukkit, just need to wait for the approval now

**Comment by jan-osicka** [comment]
Great, the plugin is now running :)  However the speed rails do not work. When I try to use the default config, there is no difference with powered rails with redstone block and normal ones. Tried several settings with multiplier, but did not work. The plugin however works as I tried the brake with soul sand and that one is working flawlessly. I do not have AC or any other plugin, which changes behaviour of rails or carts. I do not limit max speed of players in any way. There are no errors in console.

**Comment by ergor** [comment]
Just tested on spigot 1.20.4, works fine. I see that you're using paper/purpur. They do some optimizations on entities that may be interfering with the plugin. Maybe that's the issue? Have you tried using spigot?

**Comment by jan-osicka** [comment]
It works great now :) 
I tested it on spigot and it worked. Then on default paper settings and it worked as well. I have custom settings which were at the and affecting minecarts as well. Adjusted and it works now. So it was nothing with the plugin. However thank you very much for your help 👍

**Comment by ergor** [comment]
That's really good to know, as I have been getting some reports about the speed multiplier not working. It may all come down to this as you pointed out. Thanks!
